### Hit the Root
GET http://127.0.0.1:8080/

### Create a board
POST http://127.0.0.1:8080/boards/new/
content-type: application/json

{
	"title": "Fancy Project",
	"description": "this is for agile stuff!"
}

### Get all Boards
GET http://127.0.0.1:8080/boards/

### Get Board by ID
GET http://127.0.0.1:8080/boards/4

### Create Column Request
POST http://127.0.0.1:8080/boards/4/columns/new/
content-type: application/json

{
	"title": "Done",
	"order": 5
}
